### ISSUE TITLE
Hardware specification: Name of projector?

### ISSUE THREAD

**Issue by marvision-ai** [NVIDIA-Jetson/GreenMachine#1]
Hi there! Very interesting repo. What a unique idea!

I was wondering about what projector you used to show the overlaid colors? I would like to do a similar setup and was curious what you found worked out best.

Thank you :)

**Comment by nitroxplunge** [comment]
We used an AAXA P300 Pico Projector, as listed [here](https://github.com/NVIDIA-AI-IOT/GreenMachine/wiki/Hardware)
